Nick Garcia & Trevor Henderson
Monday & Wednesday

In [47]:
#https://www.kaggle.com/datasets/thedevastator/tinystories-narrative-classification

In [48]:
#Importing all necessary libraries for this algorithm
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import pandas as pd

In [49]:
#Importing a dataset full of short stories into the google colab notebook
from google.colab import files
uploaded = files.upload()
df=pd.read_csv('validation.csv')
df

Saving validation.csv to validation (3).csv

                                                    text
0      Spot. Spot saw the shiny car and said, "Wow, K...
1      Once upon a time, in a big forest, there lived...
2      Once upon a time, in a small yard, there was a...
3      Once upon a time, there was a thoughtful girl ...
4      Once upon a time, there was a kind farmer. He ...
...                                                  ...
21985  John was out in the backyard playing. He saw a...
21986  Once upon a time, there was a green vehicle. E...
21987  Once upon a time, there was a package. It was ...
21988  Once upon a time, there was a thin rhinoceros....
21989  Once there was a little girl named Sarah. She ...

[21990 rows x 1 columns]

In [50]:
#checking for any null values in the dataset
df.isnull().sum()

text    0
dtype: int64

In [51]:
#Create variables for the algotithm
#This dataset only contained one column so we had to make new labels for the text
story = df["text"].astype(str)
labels = story.apply(lambda x: 1 if len(x.split()) > 40 else 0)

In [52]:
#this tool will turn the words into numbers and help with seperating the labels
vectorizer = CountVectorizer()
#This will fit or learn all of the unique words
#converting all the words into numbers
#x is a bigtable of numbers
x = vectorizer.fit_transform(story)
#importing new libraries in order to make this classification report
#the libraries are necessary to train and test split the data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, labels, test_size=0.2)

model = MultinomialNB() # creates a blank model that is untrained
model.fit(x_train, y_train) # this will start training the model
#creates a prediction of the testing model
y_pred = model.predict(x_test)
#importing new libraries
#The rest of the code will start making the classification report

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))
print("=== STEP 3: Words converted to numbers ===")
print(f"Number of unique words found: {len(vectorizer.get_feature_names_out())}")
print(f"All unique words: {vectorizer.get_feature_names_out()}")
print()
#This model seems to be perfect as it is 1.00

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      4398

    accuracy                           1.00      4398
   macro avg       1.00      1.00      1.00      4398
weighted avg       1.00      1.00      1.00      4398

=== STEP 3: Words converted to numbers ===
Number of unique words found: 11731
All unique words: ['000' '10' '1000' ... 'šoff' 'šshall' 'šâ']

In [53]:
#we are creating a new variable and identifying if there are fake stories in the dataset
new_story = [
    "Once upon a time there was a brave knight",
    "Hi can you send the file",
]
#converting the new variables or new stories into numbers again
x_new = vectorizer.transform(new_story)

#making new predictions and geting the probability for each prediction
predictions = model.predict(x_new)
probabilities = model.predict_proba(x_new)

In [54]:
#Making the actual prediction to see if the story is real or fake
for i, email in enumerate(new_story):
   result = "Real" if predictions[i] == 1 else "Fake"
   prob_real    = probabilities[i][1] * 100
   prob_fake = probabilities[i][0] * 100

In [55]:
#Printing out the actual prediction for the stories whether its real or fake
print(f"Email: '{story}'")
print(f"  --> Prediction : {result}")
print(f"  --> Real: {prob_real:.1f}%")
print(f"  --> Fake: {prob_fake:.1f}%")
print()

Email: '0        Spot. Spot saw the shiny car and said, "Wow, K...
1        Once upon a time, in a big forest, there lived...
2        Once upon a time, in a small yard, there was a...
3        Once upon a time, there was a thoughtful girl ...
4        Once upon a time, there was a kind farmer. He ...
                               ...
21985    John was out in the backyard playing. He saw a...
21986    Once upon a time, there was a green vehicle. E...
21987    Once upon a time, there was a package. It was ...
21988    Once upon a time, there was a thin rhinoceros....
21989    Once there was a little girl named Sarah. She ...
Name: text, Length: 21990, dtype: object'
  --> Prediction : Real
  --> Real: 100.0%
  --> Fake: 0.0%

My partner and I used this dataset that consisted of short stories. This algorithm will look through the text of the short stories and find unique words to tell the difference if it a real or fake story. We did not know if there is random text that is not a short story. This algorithm trained and learned the text to tell if it is a actual short story. After running the algorithm, every text or row is identified as a real story. There is not a fake story at all in this dataset at all.